### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by miltzi** [man15h/vue-cryptoicon#4]
There is a new version available :)

https://github.com/spothq/cryptocurrency-icons/releases/tag/v0.17.1

**Comment by man15h** [comment]
Released https://github.com/man15h/vue-cryptoicon/releases/tag/v0.17.1

**Comment by tre-dev** [comment]
You're awesome. Thanks!

**Comment by slidenerd** [comment]
Keep getting this error
This dependency was not found:
* vue-cryptoicon in ./plugins/vue-cryptoicon.js
despite installing vue-cryptoicon with npm in the newer versions including 0.18 it doesnt pick it up
